use crate::error::{EsphError, Result};
use serde::{Deserialize, Serialize};

/// Join token for a worker to join the cluster.
///
/// Contains the master address, cluster name, and an authentication secret
/// generated by esph itself. Encoded as base64 for CLI copy-paste.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JoinToken {
    /// Master's IP:port (e.g. "192.168.1.100:9090")
    pub master_addr: String,
    /// Cluster name
    pub cluster_name: String,
    /// Authentication secret (esph-generated, prevents unauthorized joins)
    pub auth_secret: String,
}

impl JoinToken {
    /// Encode the token as a base64 string for CLI output.
    pub fn encode(&self) -> String {
        let json = serde_json::to_string(self).expect("JoinToken serialization cannot fail");
        use base64::Engine;
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(json.as_bytes())
    }

    /// Decode a token from a base64 string.
    pub fn decode(s: &str) -> Result<Self> {
        use base64::Engine;
        let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(s)
            .map_err(|e| EsphError::Config(format!("invalid token encoding: {}", e)))?;
        serde_json::from_slice(&bytes)
            .map_err(|e| EsphError::Config(format!("invalid token payload: {}", e)))
    }

    /// Generate the full CLI command for a worker to join.
    pub fn to_join_command(&self) -> String {
        format!(
            "esphctl init --worker --token {} --master {}",
            self.encode(),
            self.master_addr
        )
    }
}
